<?xml version="1.0"?>
<package format="3">
  <name>rover_persistent_traversability_map</name>
  <version>0.1.0</version>
  <description>
    ROS2 package that accumulates local traversability grids into a persistent OccupancyGrid map.
  </description>

  <maintainer email="samuel@example.com">Samuel Gendre</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
