persistent_traversability_map_node:
  ros__parameters:
    input_map_topic: "/traversability_grid"
    output_map_topic: "/persistent_traversability_grid"

    # Important:
    # Use "map" if you already have map -> odom.
    # Use "odom" only if you do not have global localization.
    map_frame: "map"

    # Persistent map size
    resolution: 0.10
    width_m: 500.0
    height_m: 500.0
    origin_x: -250.0
    origin_y: -250.0

    publish_rate: 2.0

    # OccupancyGrid interpretation
    lethal_threshold: 70
    free_threshold: 20

    occupied_value: 100
    free_value: 0
    unknown_value: -1
